### ISSUE TITLE
Use cases?

### ISSUE THREAD

**Issue by Clasen00** [retejs/code-plugin#1]
What exactly would be great use case for this plugin? In which moment it would be useful?

**Comment by Ni55aN** [comment]
Cogeneration is useful in at least two cases:
- executing scripts created in dataflow without running through the Engine
- running scripts in different environments (Node.js, C ++ - mainly due to performance)

**Comment by Clasen00** [comment]
@Ni55aN thank you! I think it would be cool to see this in readme)
