### ISSUE TITLE
Why inputs undefined or air?

### ISSUE THREAD

**Issue by saalaus** [retejs/code-plugin#4]
Why do inputs or undefined or air? As fill inputs?

**Comment by Ni55aN** [comment]
Please specify your question in more detail

**Comment by saalaus** [comment]
Worker have a inputs and outputs, as use outputs and outputs in code?

**Comment by Ni55aN** [comment]
Readme contains an example https://github.com/retejs/code-plugin#code

**Comment by saalaus** [comment]
I have inputs in empty
```
code(node, inputs, add) {
        add('num', node.data.time)
        console.log(inputs)
    }

>>inputs:[undefined]
```

**Comment by Ni55aN** [comment]
NumComponent does not have inputs

**Comment by saalaus** [comment]
I use my component, my component have inputs

```
class Text extends Rete.Component {
    constructor() {
        super('Text');
    }

    builder(node) {
        var prev = node.addInput(new Rete.Input('prev', "", anyType, false))
        var next = node.addOutput(new Rete.Output('next', "", anyType, false))
    }

    code(node, inputs, add) {
       add('name', "test")
        console.log(inputs)
    }
}
```

**Comment by Ni55aN** [comment]
It looks like nothing is passed to this socket. Which node is connected before?

**Comment by saalaus** [comment]
If node connecting before -> array [undefined], else -> array is empty
(I connected 2 identical nodes)

1 node: input array empty
2 node: input array empty
![default](https://user-images.githubusercontent.com/37474917/47783554-d3fe0000-dd24-11e8-9422-abb76493686e.png)

1 node: input array empty
2 node: input array [undefined]
![default](https://user-images.githubusercontent.com/37474917/47783584-e8da9380-dd24-11e8-9cf0-89d784f885fd.png)

**Comment by Ni55aN** [comment]
Does the left node has `add('next', "some value")` in worker?
