### ISSUE TITLE
how can i use this plugin

### ISSUE THREAD

**Issue by tortorse** [retejs/code-plugin#5]
I used this plugin followed the README, but there is an error

> e.components.map is not a function

I found `engine.components` is a `Map`,but the plugin's input is a `Array`?
Maybe i didn't use it in the right way?

rete version: 1.3.0
rete-code-plugin version: 0.1.1

**Comment by Ni55aN** [comment]
I need to see a full call trace

**Comment by tortorse** [comment]
Here is the code. https://codesandbox.io/s/vue-template-3ocyi?fontsize=14

**Comment by Hatead1** [comment]
I confirm, the same error.

**Comment by Ni55aN** [comment]
fixed in `v0.2.0`. Rete CLI was updated, so [take into account](https://rete.js.org/#/docs#lang=en&tosearch=and%20use%20UMD%20modules%3A)

```js
import CodePlugin, { generate } from 'rete-code-plugin';
```

**Comment by Ni55aN** [comment]
A long time I'm planning to generate a code from AST, therefore plugin can have breaking changes

**Comment by Hatead1** [comment]
And 
`          const sourceCode = await generate(engine, editor.toJSON());`

**Comment by Hatead1** [comment]
> generate a code from AST

may be another plugin? ast-code-plugin or something like that?

**Comment by Hatead1** [comment]
"c.code is not a function" if no code() function in component. But if component shouldn't generate code?

**Comment by Ni55aN** [comment]
`code() {}`

**Comment by Hatead1** [comment]
Thanks!

**Comment by tortorse** [comment]
Thanks a lot!
